### ISSUE TITLE
es6 module?

### ISSUE THREAD

**Issue by mbykov** [josudoey/js-jieba#1]
Hi,

are you planning to rewrite js-jieba as a es6 module?

For now I've got 

import { Jieba } from 'js-jieba'
import { JiebaDict, HMMModel, UserDict, IDF, StopWords } from 'js-jieba/dist/dict.zh-cn'

ReferenceError: module is not defined
    at eval (/node_modules/js-jieba/dist/dict.zh-cn.js:3:1)

**Comment by josudoey** [comment]
this is great recommendation~

**Comment by josudoey** [comment]
the workaround solution.
you can use 
```
import { createRequire } from 'module'
const {
    JiebaDict, HMMModel, UserDict, IDF, StopWords
} = createRequire(import.meta.url)('js-jieba/dist/dict.zh-cn.js')
```

**Comment by josudoey** [comment]
I need find the solution for how to make es6 module dict.

**Comment by josudoey** [comment]
hihi~ after v1.0.8 you can use es6 module for dict
```mjs
import {
  JiebaDict, HMMModel,
  UserDict, IDF, StopWords
} from 'jieba-zh-tw'
import createJieba from 'js-jieba'

const jieba = createJieba(
  Buffer.from(JiebaDict),
  Buffer.from(HMMModel),
  Buffer.from(UserDict),
  Buffer.from(IDF),
  Buffer.from(StopWords)
)
```
